import { Slide, Lecture } from './teachingData';

const RULES_GAMING: string[] = [
  'When we arrive, open Replit and wait — do not touch anyone else\'s project',
  'Raise your hand before speaking. Everyone\'s build time is valuable.',
  'Keep your hands off other people\'s keyboards and trackpads',
  'Stay on task — games, YouTube, and social media are closed during class',
  'Save constantly: your Replit auto-saves but always check the top bar says "Saved"',
  'Treat the laptops with care — close gently, no food or drinks nearby',
  'Feedback rule: "I noticed..." not "your game is bad." Be specific and kind.',
  'Bugs are normal. Asking for help is smart. Suffering silently is not.',
];

export const GAMING_SESSIONS: Lecture[] = [

  // ══════════════════════════════════════════════════════════
  //  DAY 1 — How Games Store Data
  // ══════════════════════════════════════════════════════════
  {
    id: 'day1',
    num: 0,
    title: 'How Games Store Data',
    theme: 'Apr 6 · In-Person · Lehman College',
    slides: [
      {
        type: 'title',
        heading: 'How Games\nStore Data',
        label: 'Day 1 · Pacman Bootcamp · UAU / Lehman STEP',
      },
      {
        type: 'rules',
        label: '— Bootcamp Rules',
        items: RULES_GAMING,
      },
      {
        type: 'question',
        label: '— Icebreaker',
        heading: 'What\'s your favorite level in any game — and why does it feel so good?',
        body: 'A great level isn\'t an accident. Every wall, enemy, shortcut, and power-up was placed on purpose. Today we\'re going to figure out exactly how a computer stores that information — and then design our own.',
        items: [
          'Name a level you love. What makes it memorable — the layout, the challenge, the vibe?',
          'Have you ever felt a level was unfair or too easy? What was broken about the design?',
          'If you designed a Pacman maze right now, what\'s the first thing you\'d change about the classic?',
        ],
      },
      {
        type: 'visual',
        label: '— What Is Pacman?',
        heading: 'Breaking Pacman Into Pieces',
        body: 'Before we write a single line of code, let\'s understand what Pacman actually is. Every game is just data + rules. Pacman has four pieces.',
        cards: [
          { icon: '🗺️', title: 'A Maze', body: 'A grid of walls and paths. Every cell in the grid is either a wall, a path, a pellet, or a power pellet. The maze is just a big table of numbers.' },
          { icon: '🟡', title: 'A Player', body: 'A position on that grid. Pacman\'s location is just two numbers — which row and which column he\'s currently on. Movement = changing those numbers.' },
          { icon: '👻', title: 'Ghosts', body: 'Enemies that also have positions. Each ghost has its own row and column, plus a simple rule for how it decides to move.' },
          { icon: '⚫', title: 'Pellets', body: 'Data stored in the maze grid itself. When Pacman moves to a cell that has a pellet (value = 2), the pellet disappears and the score increases.' },
        ],
      },
      {
        type: 'concept',
        label: '— p5.js Basics',
        heading: 'How p5.js Works: setup() and draw()',
        body: 'p5.js runs your game in two functions. You don\'t call them — p5.js calls them for you automatically, on a strict schedule. This is the entire skeleton of every p5.js sketch:',
        items: [
          'function setup() {',
          '  // Runs ONCE when the page loads.',
          '  // Use this to create the canvas and set starting values.',
          '  createCanvas(420, 420);',
          '}',
          '',
          'function draw() {',
          '  // Runs 60 TIMES PER SECOND — forever.',
          '  // Use this to draw your game every frame.',
          '  background(0);  // wipe the screen black each frame',
          '  drawMaze();     // draw the maze on top',
          '}',
          '',
          '⚠️  setup() creates the canvas. draw() redraws it. Never swap them.',
          '⚠️  background() must be inside draw() or old frames pile up.',
        ],
      },
      {
        type: 'concept',
        label: '— The Grid',
        heading: 'A Grid Is Just Numbers',
        body: 'The Pacman maze looks like art, but internally it\'s just a table of numbers. Each number tells the computer what to draw in that cell. Here\'s a tiny 5×5 example:',
        items: [
          '  [1, 1, 1, 1, 1]   ← row 0 (all walls = top border)',
          '  [1, 0, 2, 0, 1]   ← row 1 (walls on edges, path + pellet in middle)',
          '  [1, 0, 1, 0, 1]   ← row 2 (wall pillar in center)',
          '  [1, 0, 2, 0, 1]   ← row 3 (path + pellet)',
          '  [1, 1, 1, 1, 1]   ← row 4 (all walls = bottom border)',
          '',
          '0 = PATH      → empty floor, Pacman can walk here',
          '1 = WALL      → solid block, nobody can pass through',
          '2 = PELLET    → small dot, eaten for points',
          '3 = POWER     → large dot, lets Pacman eat ghosts',
          '',
          'That\'s it. The entire maze is just 0s, 1s, 2s, and 3s.',
        ],
      },
      {
        type: 'concept',
        label: '— 2D Arrays',
        heading: 'The 2D Array: Storing the Maze in Code',
        body: 'In JavaScript, a 2D array is an array of arrays. Each inner array is one row of the maze. Here\'s exactly how you write it:',
        items: [
          'let maze = [',
          '  [1, 1, 1, 1, 1],  // row 0',
          '  [1, 0, 2, 0, 1],  // row 1',
          '  [1, 0, 1, 0, 1],  // row 2',
          '  [1, 0, 2, 0, 1],  // row 3',
          '  [1, 1, 1, 1, 1],  // row 4',
          '];',
          '',
          '// To read a value: maze[row][col]',
          'console.log( maze[1][2] );  // → 2  (that\'s a pellet!)',
          'console.log( maze[0][0] );  // → 1  (that\'s a wall)',
          'console.log( maze[2][2] );  // → 1  (the center pillar)',
          '',
          '⚠️  Always [row][col] — NOT [col][row]. Row first, column second.',
          '⚠️  Rows count DOWN from the top. Row 0 is the TOP row.',
        ],
      },
      {
        type: 'concept',
        label: '— Constants',
        heading: 'Setting Up Constants at the Top',
        body: 'Before the maze array, we define constants — fixed values we use everywhere. Write these at the very top of your sketch, outside both setup() and draw():',
        items: [
          'const TILE_SIZE = 20;  // each cell is 20×20 pixels',
          'const COLS = 21;       // maze is 21 columns wide',
          'const ROWS = 21;       // maze is 21 rows tall',
          '',
          'const PATH  = 0;  // empty floor',
          'const WALL  = 1;  // solid wall',
          'const PELLET = 2; // small dot',
          'const POWER  = 3; // big power pellet',
          '',
          '// These make the canvas exactly the right size:',
          '// width  = COLS * TILE_SIZE = 21 * 20 = 420 pixels',
          '// height = ROWS * TILE_SIZE = 21 * 20 = 420 pixels',
          '',
          '// In setup(), use these:',
          'function setup() {',
          '  createCanvas(COLS * TILE_SIZE, ROWS * TILE_SIZE);',
          '}',
          '',
          '💡 Why constants? If you want a bigger maze, change TILE_SIZE = 30',
          '   and EVERYTHING updates automatically. No hunting through the code.',
        ],
      },
      {
        type: 'concept',
        label: '— Nested Loops',
        heading: 'The Nested For Loop: Visiting Every Cell',
        body: 'To draw the maze, we need to visit every cell — every row, every column. A single for loop visits one row. A nested for loop (loop inside a loop) visits every cell in every row:',
        items: [
          'for (let row = 0; row < ROWS; row++) {',
          '  // This runs once per row (21 times total)',
          '',
          '  for (let col = 0; col < COLS; col++) {',
          '    // This runs once per CELL in this row (21 times)',
          '    // Together: 21 rows × 21 cols = 441 cells visited',
          '',
          '    let cell = maze[row][col];  // what\'s in this cell?',
          '',
          '    // Now we can decide what to draw here...',
          '  }',
          '}',
          '',
          '⚠️  Outer loop = rows (up/down). Inner loop = cols (left/right).',
          '⚠️  maze[row][col] — row goes with the OUTER loop, col with INNER.',
          '💡 Think of it like reading a book: left to right, then next line down.',
        ],
      },
      {
        type: 'concept',
        label: '— Pixel Math',
        heading: 'From Grid Coordinates to Pixels',
        body: 'The maze uses grid coordinates (row, col). The canvas uses pixel coordinates (x, y). We need to convert. Each cell is TILE_SIZE pixels wide and tall:',
        items: [
          '// Formula:',
          'let x = col * TILE_SIZE;  // pixel X position (left edge of cell)',
          'let y = row * TILE_SIZE;  // pixel Y position (top edge of cell)',
          '',
          '// Example: the cell at row=2, col=3',
          'let x = 3 * 20;  // = 60 pixels from left',
          'let y = 2 * 20;  // = 40 pixels from top',
          '',
          '// So rect(x, y, TILE_SIZE, TILE_SIZE) draws a 20×20 box',
          '// starting at pixel (60, 40) — exactly cell (row=2, col=3)',
          '',
          '// Visual check:',
          '//   col 0 → x = 0   (leftmost column)',
          '//   col 1 → x = 20  (second column)',
          '//   col 20 → x = 400 (rightmost column of 21 total)',
          '',
          '💡 This is the ONLY math in the whole maze system. Memorize it.',
        ],
      },
      {
        type: 'concept',
        label: '— Drawing Tiles',
        heading: 'Drawing Each Cell: If / Else Chains',
        body: 'Inside the nested loop, we check what value is in the cell and draw the right shape. We use fill() to set the color, then rect() or circle() to draw:',
        items: [
          'if (cell === WALL) {',
          '  fill(0, 0, 180);     // blue walls',
          '  noStroke();          // no outline',
          '  rect(x, y, TILE_SIZE, TILE_SIZE);',
          '',
          '} else if (cell === PELLET) {',
          '  fill(0);             // black background for this cell',
          '  rect(x, y, TILE_SIZE, TILE_SIZE);',
          '  fill(255, 255, 200); // pale yellow dot',
          '  circle(x + TILE_SIZE/2, y + TILE_SIZE/2, 5);  // centered dot',
          '',
          '} else if (cell === POWER) {',
          '  fill(0);',
          '  rect(x, y, TILE_SIZE, TILE_SIZE);',
          '  fill(255, 180, 0);   // orange power pellet',
          '  circle(x + TILE_SIZE/2, y + TILE_SIZE/2, 12); // bigger dot',
          '',
          '} else {               // PATH — just empty floor',
          '  fill(0);             // black',
          '  rect(x, y, TILE_SIZE, TILE_SIZE);',
          '}',
          '',
          '💡 circle(cx, cy, diameter) — cx and cy are the CENTER, not the corner.',
          '   rect(x, y, w, h)    — x and y are the TOP-LEFT corner.',
        ],
      },
      {
        type: 'concept',
        label: '— Full Function',
        heading: 'Putting It All Together: drawMaze()',
        body: 'Here\'s the complete drawMaze() function. Every line has been explained in the slides above — this is just all of it assembled in one place:',
        items: [
          'function drawMaze() {',
          '  for (let row = 0; row < ROWS; row++) {',
          '    for (let col = 0; col < COLS; col++) {',
          '',
          '      let cell = maze[row][col];',
          '      let x = col * TILE_SIZE;',
          '      let y = row * TILE_SIZE;',
          '',
          '      if (cell === WALL) {',
          '        fill(0, 0, 180);',
          '        noStroke();',
          '        rect(x, y, TILE_SIZE, TILE_SIZE);',
          '',
          '      } else if (cell === PELLET) {',
          '        fill(0); rect(x, y, TILE_SIZE, TILE_SIZE);',
          '        fill(255, 255, 200);',
          '        circle(x + TILE_SIZE/2, y + TILE_SIZE/2, 5);',
          '',
          '      } else if (cell === POWER) {',
          '        fill(0); rect(x, y, TILE_SIZE, TILE_SIZE);',
          '        fill(255, 180, 0);',
          '        circle(x + TILE_SIZE/2, y + TILE_SIZE/2, 12);',
          '',
          '      } else {',
          '        fill(0);',
          '        rect(x, y, TILE_SIZE, TILE_SIZE);',
          '      }',
          '    }',
          '  }',
          '}',
          '',
          'Call this from inside draw() after background(0).  That\'s it!',
        ],
      },
      {
        type: 'concept',
        label: '— Debugging',
        heading: 'Common Errors and How to Fix Them',
        body: 'Your maze will break. That\'s normal. Here are the five most common mistakes — check these before asking for help:',
        items: [
          '❌  White screen / nothing appears',
          '    → Did you call drawMaze() inside draw()?',
          '    → Is createCanvas() in setup()?',
          '',
          '❌  "maze is not defined" error',
          '    → Your maze array was defined inside a function. Move it to the TOP of the file.',
          '',
          '❌  Maze draws but is cut off / overflows the canvas',
          '    → Count your rows and columns. You probably have more than ROWS or COLS.',
          '    → Columns in each row must ALL be the same length.',
          '',
          '❌  Pellets are invisible',
          '    → You need two fill() calls: one for the black background square,',
          '       then one for the dot. Both must be inside the PELLET branch.',
          '',
          '❌  TypeError: Cannot read properties of undefined (reading \'0\')',
          '    → maze[row] is undefined. You have a row with the wrong number of values.',
          '    → Open console (F12), look at the row number in the error.',
          '',
          '💡 Use console.log(maze[row][col]) inside the loop to inspect values.',
        ],
      },
      {
        type: 'visual',
        label: '— Design Rules',
        heading: 'What Makes a Good Maze?',
        body: 'Before you design on paper, here are the rules. Break them and your maze will be unplayable or unsolvable.',
        cards: [
          { icon: '🔒', title: 'Always Wall the Border', body: 'Row 0, row 20, col 0, and col 20 must ALL be 1s. If Pacman escapes the border, the game breaks. Every maze must have a complete outer wall.' },
          { icon: '🔗', title: 'All Paths Must Connect', body: 'Every PATH cell (0) must be reachable from every other. If part of your maze is walled off, Pacman can never collect all pellets — the game is unwinnable.' },
          { icon: '⚖️', title: 'Balance Danger and Safety', body: 'If the maze is one long corridor, it\'s boring. If every path dead-ends, it\'s frustrating. Aim for: multiple routes, at least 2–3 escape paths near each power pellet.' },
          { icon: '🎯', title: 'Power Pellets in the Corners', body: 'Classic Pacman puts power pellets at the four corners. It\'s a design choice: corners are the most dangerous spots (easy to get trapped), so the reward lives there.' },
        ],
      },
      {
        type: 'concept',
        label: '— Design Activity',
        heading: 'Paper Maze Design: Your Turn',
        body: 'Before coding, design your maze on paper. You have a 21×21 grid. Rules: the outer border must be all 1s. Every path cell must connect. Place exactly 4 power pellets (3s). Fill the rest with 0s (paths) and 2s (pellets).',
        items: [
          'Step 1: Draw the 21×21 grid on paper. Number rows 0–20 (top to bottom)',
          '         and columns 0–20 (left to right).',
          '',
          'Step 2: Fill the outer border (row 0, row 20, col 0, col 20) with 1s.',
          '',
          'Step 3: Sketch your wall layout. Think about: main corridors,',
          '         small pockets, choke points, open rooms, dead-ends.',
          '',
          'Step 4: Place 4 power pellets (3s) — typically near corners.',
          '',
          'Step 5: Everywhere Pacman can walk = 2 (pellet). Start point = 0 (no pellet).',
          '',
          'Step 6: Check connectivity. Trace a path from the center to every corner.',
          '         If you can\'t reach it, you need to remove a wall.',
          '',
          '💡 The classic Pacman maze has 240 pellets and 4 power pellets.',
          '   You don\'t need that many — a 21×21 grid with ~100 pellets is great.',
        ],
      },
      {
        type: 'challenge',
        challengeNum: 1,
        label: '— Challenge 01',
        heading: 'Get Your Maze on Screen',
        body: 'Open the starter Replit project (link on the board). Your starter code already has the constants, the maze variable, and the drawMaze() function stub. Your job: (1) Fill in the maze array with your paper design. Every row must have exactly 21 values. (2) Complete the drawMaze() if/else block with the four tile types. (3) Press the Run button. You should see your maze. Fix any errors using the debugging guide on the previous slide.',
      },
    ] as Slide[],
  },

  // ══════════════════════════════════════════════════════════
  //  DAY 2 — Game Feel
  // ══════════════════════════════════════════════════════════
  {
    id: 'day2',
    num: 1,
    title: 'Game Feel',
    theme: 'Apr 7 · In-Person · Lehman College',
    slides: [
      {
        type: 'title',
        heading: 'Game Feel',
        label: 'Apr 7 · In-Person · Lehman College',
      },
      {
        type: 'concept',
        label: '— Animation',
        heading: 'Choosing Animations Based on Direction',
        body: 'Add this block at the end of _process(), after the position update. It picks the right animation and flips the sprite so you don\'t need separate left/right/down frames:',
        items: [
          'if velocity.x != 0:',
          '    $AnimatedSprite2D.animation = "walk"',
          '    $AnimatedSprite2D.flip_v = false',
          '    $AnimatedSprite2D.flip_h = velocity.x < 0  # flip left',
          'elif velocity.y != 0:',
          '    $AnimatedSprite2D.animation = "up"',
          '    $AnimatedSprite2D.flip_v = velocity.y > 0  # flip down',
          'flip_h = velocity.x < 0 is a boolean shorthand: if x is negative (moving left), flip_h becomes true',
          'Run the scene again — the sprite should now face the correct direction for all 4 directions',
        ],
      },
      {
        type: 'concept',
        label: '— Signals',
        heading: 'Detecting Collisions with Signals',
        body: 'Signals are Godot\'s event system — nodes broadcast signals when something happens, and other nodes listen. We need the player to detect when an enemy touches it.',
        items: [
          'At the top of player.gd, after "extends Area2D", add:',
          'signal hit',
          '',
          'In the Inspector → Node tab → Signals → find body_entered(body) → click Connect',
          'Godot creates: func _on_body_entered(_body):',
          'Fill it in:',
          '    hide()',
          '    hit.emit()',
          '    $CollisionShape2D.set_deferred("disabled", true)',
          'set_deferred is required — you can\'t change collision shapes mid-physics frame',
          'Also add a start() function for resetting: func start(pos): position = pos / show() / $CollisionShape2D.disabled = false',
        ],
      },
      {
        type: 'concept',
        label: '— Enemy Scene',
        heading: 'Creating the Mob — Node Setup',
        body: 'Scene → New Scene → Other Node → RigidBody2D. Rename it Mob. Add these children:',
        items: [
          'AnimatedSprite2D — 3 animations: "fly", "swim", "walk" (2 frames each from art/ folder)',
          'Set Animation Speed to 3 for all three animations',
          'Set AnimatedSprite2D Scale to (0.75, 0.75)',
          'CollisionShape2D → New CapsuleShape2D → set Rotation to 90 in Transform',
          'VisibleOnScreenNotifier2D — auto-deletes the mob when it leaves the screen',
          'On the Mob (RigidBody2D) node: set Gravity Scale to 0 (under RigidBody2D in Inspector)',
          'Collision section → Mask → uncheck layer 1 so mobs don\'t collide with each other',
          'Save as mob.tscn',
        ],
      },
      {
        type: 'concept',
        label: '— Enemy Script',
        heading: 'Mob Script — Random Animation & Auto-Delete',
        body: 'Attach a script to the Mob node (extends RigidBody2D). The mob picks a random animation on spawn and deletes itself when it leaves the screen:',
        items: [
          'extends RigidBody2D',
          '',
          'func _ready():',
          '    var mob_types = Array($AnimatedSprite2D.sprite_frames.get_animation_names())',
          '    $AnimatedSprite2D.animation = mob_types.pick_random()',
          '    $AnimatedSprite2D.play()',
          '',
          'Connect VisibleOnScreenNotifier2D → screen_exited() signal → Mob node',
          'Godot creates: func _on_visible_on_screen_notifier_2d_screen_exited():',
          '    queue_free()  # removes the node from the scene entirely',
          'pick_random() picks one element randomly from an array — ["walk", "swim", "fly"]',
        ],
      },
      {
        type: 'visual',
        label: '— Game Feel',
        heading: 'What Makes a Game Feel Good',
        body: 'Game feel is the invisible layer that separates "it works" from "I can\'t stop playing." These are the four elements that create it.',
        cards: [
          { icon: '⚡', title: 'Responsiveness', body: 'Zero delay between input and result. The player presses jump and it happens that frame — not 100ms later.' },
          { icon: '🎯', title: 'Precision', body: 'The character does exactly what you asked. Normalized velocity (no faster diagonals), position clamping (no leaving the screen).' },
          { icon: '💥', title: 'Impact', body: 'Every action has feedback — animation, sound, or visual effect. Our hide() on hit is the simplest form of impact.' },
          { icon: '📈', title: 'Stakes', body: 'Something to lose (getting hit), something to gain (score). Without stakes it\'s a demo, not a game.' },
        ],
      },
      {
        type: 'challenge',
        challengeNum: 2,
        label: '— Challenge 02',
        heading: 'Enemies on Screen',
        body: 'Test your Mob scene by pressing F6 from mob.tscn. You should see a random animal animation playing. If the animation shows "null": check AnimatedSprite2D SpriteFrames has frames in all three animations. If it shows a warning triangle on CollisionShape2D: the CapsuleShape2D hasn\'t been sized yet — drag the handles to cover the sprite.',
      },
    ] as Slide[],
  },

  // ══════════════════════════════════════════════════════════
  //  DAY 3 — Make It Yours
  // ══════════════════════════════════════════════════════════
  {
    id: 'day3',
    num: 2,
    title: 'Make It Yours',
    theme: 'Apr 8 · In-Person · Lehman College',
    slides: [
      {
        type: 'title',
        heading: 'Make It\nYours',
        label: 'Apr 8 · In-Person · Lehman College',
      },
      {
        type: 'concept',
        label: '— Main Scene',
        heading: 'The Main Scene — Bringing It All Together',
        body: 'Scene → New Scene → Node (not Node2D — this scene handles logic, not visuals). Name it Main. Now instance your scenes and add timers:',
        items: [
          'Instance Player: click the chain-link icon → select player.tscn',
          'Add child Timer → rename MobTimer → Wait Time: 0.5s',
          'Add child Timer → rename ScoreTimer → Wait Time: 1s',
          'Add child Timer → rename StartTimer → Wait Time: 2s → One Shot: On',
          'Add child Marker2D → rename StartPosition → Position: (240, 450)',
          'Add child Path2D → rename MobPath → draw a rectangle around the screen edges (clockwise!)',
          'Add child PathFollow2D under MobPath → rename MobSpawnLocation',
          'Save as main.tscn. Right-click it in FileSystem → Set As Main Scene',
        ],
      },
      {
        type: 'concept',
        label: '— Main Script',
        heading: 'Spawning Mobs — The Main Script',
        body: 'Attach a script to Main (extends Node). The mob timer fires every 0.5s and spawns a new mob at a random edge position:',
        items: [
          'extends Node',
          '@export var mob_scene: PackedScene',
          'var score',
          '',
          'func game_over(): $ScoreTimer.stop() / $MobTimer.stop()',
          'func new_game(): score = 0 / $Player.start($StartPosition.position) / $StartTimer.start()',
          'func _on_start_timer_timeout(): $MobTimer.start() / $ScoreTimer.start()',
          'func _on_score_timer_timeout(): score += 1',
          'func _on_mob_timer_timeout():',
          '    var mob = mob_scene.instantiate()',
          '    var loc = $MobPath/MobSpawnLocation',
          '    loc.progress_ratio = randf()',
          '    var direction = loc.rotation + PI / 2 + randf_range(-PI/4, PI/4)',
          '    mob.position = loc.position / mob.rotation = direction',
          '    mob.linear_velocity = Vector2(randf_range(150,250), 0).rotated(direction)',
          '    add_child(mob)',
          'In Inspector, drag mob.tscn into the Mob Scene property. Connect Player hit signal → game_over()',
        ],
      },
      {
        type: 'concept',
        label: '— HUD',
        heading: 'The HUD — Score, Messages & Start Button',
        body: 'Scene → New Scene → Other Node → CanvasLayer → name it HUD. Add these children (all use font Xolonium-Regular.ttf at size 64):',
        items: [
          'Label → rename ScoreLabel → text: "0" → Anchor Preset: Center Top → Horizontal Alignment: Center',
          'Label → rename Message → text: "Dodge the Creeps!" → Anchor Preset: Center → Autowrap: Word → Size X: 480',
          'Button → rename StartButton → text: "Start" → Anchor Preset: Center Bottom → Size: 200×100 → Position Y: 580',
          'Timer → rename MessageTimer → Wait Time: 2 → One Shot: On',
          '',
          'HUD script (extends CanvasLayer):',
          'signal start_game',
          'func show_message(text): $Message.text = text / $Message.show() / $MessageTimer.start()',
          'func update_score(score): $ScoreLabel.text = str(score)',
          'func _on_start_button_pressed(): $StartButton.hide() / start_game.emit()',
          'func _on_message_timer_timeout(): $Message.hide()',
          'func show_game_over(): show_message("Game Over") / await $MessageTimer.timeout / ... / $StartButton.show()',
        ],
      },
      {
        type: 'concept',
        label: '— Connecting',
        heading: 'Connecting HUD to Main',
        body: 'Instance hud.tscn as a child of Main. Now wire the signals together so score, game over, and new game all work:',
        items: [
          'In Main Node tab: connect HUD start_game signal → new_game() function',
          'In new_game(): add $HUD.update_score(score) and $HUD.show_message("Get Ready")',
          'In game_over(): add $HUD.show_game_over()',
          'In _on_score_timer_timeout(): add $HUD.update_score(score)',
          '',
          'Clean up mobs on new game — add to new_game():',
          'get_tree().call_group("mobs", "queue_free")',
          'For this to work: open mob.tscn → select Mob node → Groups tab → add group "mobs"',
          '',
          'Press F5. Click Start. Dodge enemies. Score counts up. Getting hit shows Game Over.',
        ],
      },
      {
        type: 'examples',
        label: '— Your Game',
        heading: 'What Kind of Game Do You Want to Build?',
        body: 'You\'ve just built Dodge the Creeps from scratch. Now you know the fundamentals: scenes, nodes, scripts, signals, timers. Pick a genre and start your own.',
        items: [
          'Platformer — gravity, jumping, platforms, collectibles',
          'Top-Down Adventure — 4-directional movement, rooms, NPCs',
          'Puzzle Game — logic over action, no enemies needed',
          'Shooter / Shmup — fire projectiles, wave-based enemies',
          'RPG / Story Game — stats, dialogue, exploration',
          'Tower Defense — place units, manage resources, survive waves',
          'Endless Runner — auto-scroll, obstacle dodging, high score',
        ],
      },
      {
        type: 'project',
        label: '— GDD',
        heading: 'Your Game Design Document',
        body: 'A GDD is a 1-page written plan. It forces you to think before you build — cutting down on "I don\'t know what to do next." Fill out these five sections before you open Godot on your own game.',
      },
      {
        type: 'challenge',
        challengeNum: 3,
        label: '— Challenge 03',
        heading: 'Start Your Own Game',
        body: 'Fork Dodge the Creeps and modify it toward your genre — or start a new scene from scratch. By the end of today: your GDD is filled in, you have chosen a genre, and you have at least one node in a new scene. The template from Days 1-2 is your reference. Everything you need is already in your project.',
      },
    ] as Slide[],
  },

  // ══════════════════════════════════════════════════════════
  //  DAY 4 — Prototype Sprint
  // ══════════════════════════════════════════════════════════
  {
    id: 'day4',
    num: 3,
    title: 'Prototype Sprint',
    theme: 'Apr 9 · In-Person · Lehman College',
    slides: [
      {
        type: 'title',
        heading: 'Prototype\nSprint',
        label: 'Apr 9 · In-Person · Lehman College',
      },
      {
        type: 'concept',
        label: '— Polish',
        heading: 'Background & Audio — The Final Layer',
        body: 'These two things — a background and sound — are the fastest way to make your game feel real. Both take under 10 minutes in Godot.',
        items: [
          'Background: in Main scene, add ColorRect as the FIRST child (so it draws behind everything)',
          'ColorRect → Inspector → Color → pick your color',
          'Layout → Anchor Preset → Full Rect (fills the entire window)',
          '',
          'Audio: add two AudioStreamPlayer nodes to Main',
          'Rename them Music and DeathSound',
          'Music → Stream → Load → "House In a Forest Loop.ogg" → check Loop',
          'DeathSound → Stream → Load → "gameover.wav"',
          'In new_game(): $Music.play()',
          'In game_over(): $Music.stop() / $DeathSound.play()',
          'Keyboard shortcut: Project Settings → Input Map → add "start_game" → map to Enter key → set on StartButton\'s Shortcut property',
        ],
      },
      {
        type: 'concept',
        label: '— Export',
        heading: 'Exporting & Sharing on itch.io',
        body: 'Godot can export your game to a web page — no install required. Anyone with a browser can play it.',
        items: [
          'Project → Export → Add → Web (HTML5)',
          'Click "Manage Export Templates" → Download if prompted',
          'Set the export path to a new folder, e.g. export/index.html',
          'Click Export Project → keep "index.html" as the filename',
          'Go to itch.io → Create new project → set Kind to HTML',
          'Upload the entire export/ folder as a ZIP',
          'Check "This file will be played in the browser" → Save',
          'Share the link — anyone in the world can play your game instantly',
        ],
      },
      {
        type: 'project',
        label: '— Build Sprint',
        heading: '90 Minutes. Heads Down.',
        body: 'This is the longest uninterrupted build block of the bootcamp. No new concepts — just you and your game. Instructors are circulating. Raise your hand for 1:1 help. If you\'re stuck for more than 5 minutes, ask — debugging alone is not a learning strategy.',
      },
      {
        type: 'concept',
        label: '— Playtesting',
        heading: 'How to Give Good Playtest Feedback',
        body: 'In 15 minutes we swap laptops. Playing someone else\'s game and giving useful notes is a skill. Here\'s how:',
        items: [
          'Describe what you experienced — not what you think they should do',
          '"I didn\'t know where to go after collecting the coin" — specific and useful',
          '"It\'s confusing" — vague and not useful',
          'Name one thing that worked — every game has something, find it',
          'Ask a question instead of giving orders: "What happens when you fall?" not "Add a respawn"',
          'Two strengths, one thing to explore. Not a list of problems.',
        ],
      },
      {
        type: 'challenge',
        challengeNum: 4,
        label: '— Challenge 04',
        heading: 'Set 3 Goals for Saturday Sessions',
        body: 'Before you leave: write down 3 specific, buildable goals for the May Saturday sessions. Not "make it better" — real goals like "add a second level scene", "make the player respawn at a checkpoint", or "add a score counter that resets on death." Share them with an instructor before you pack up.',
      },
    ] as Slide[],
  },

  // ══════════════════════════════════════════════════════════
  //  ASYNC 1 — Game Design Document
  // ══════════════════════════════════════════════════════════
  {
    id: 'async1',
    num: 4,
    title: 'Game Design Document',
    theme: 'Async · Self-Paced · ~45 min · Due May 2',
    slides: [
      {
        type: 'title',
        heading: 'Game Design\nDocument',
        label: 'Async 1 · Self-Paced · Due Before May 2',
      },
      {
        type: 'concept',
        label: '— What & Why',
        heading: 'What Is a GDD and Why Does It Matter?',
        body: 'A Game Design Document is a written plan for your game. Every studio writes one before writing code. For you it does one specific thing: it means you never stare at Godot wondering what to do next.',
        items: [
          'Forces you to think through your game before you touch a node',
          'Gives you a reference to return to when you lose focus mid-session',
          'Dramatically reduces "I don\'t know what to do next" moments',
          'Instructors will read yours and leave specific feedback before May 2',
          'Students with clear GDDs build faster and finish stronger — every time',
        ],
      },
      {
        type: 'concept',
        label: '— Five Questions',
        heading: 'Answer These Five Things',
        body: 'Write in full sentences. Be specific. Vague answers create vague games. Aim for ~45 minutes total.',
        items: [
          '1. What is your game called? Write a 2-sentence pitch: what does the player do, and why is it fun?',
          '2. Who is the main character? What can they do — movement, abilities, any limitations?',
          '3. What is the goal? How does the player win? How do they lose?',
          '4. What are your 3 core mechanics — the 3 things the player can actually do in your game?',
          '5. What does your first level look like? Describe it in 3+ sentences OR include a sketch',
        ],
      },
      {
        type: 'challenge',
        challengeNum: 5,
        label: '— Submit',
        heading: 'Submit Before May 2',
        body: 'Instructors will review every GDD and leave written feedback before the first Saturday session. The more specific your GDD, the more specific the feedback. "Platformer game where you jump" gets a generic response. "Platformer where a kid explores their late grandmother\'s house, and each room unlocks a memory" gets real notes.',
      },
    ] as Slide[],
  },

  // ══════════════════════════════════════════════════════════
  //  ASYNC 2 — Playtest Log
  // ══════════════════════════════════════════════════════════
  {
    id: 'async2',
    num: 5,
    title: 'Playtest Log',
    theme: 'Async · Self-Paced · ~45 min · Due May 16',
    slides: [
      {
        type: 'title',
        heading: 'Playtest\nLog',
        label: 'Async 2 · Self-Paced · Due Before May 16',
      },
      {
        type: 'concept',
        label: '— What Is a Playtest?',
        heading: 'Watch Someone Else Play Your Game',
        body: 'A playtest is sitting someone down with your game and watching — silently — without giving instructions. You can\'t playtest your own game because you already know how it works. You need fresh eyes.',
        items: [
          'Find a friend or family member who has never seen your game',
          'Set them up, press Play, and step back — do not explain anything',
          'Watch their screen. Take notes. Do not react to their choices.',
          'Only help if they\'ve been stuck for 2+ minutes with no progress',
          'When they finish: "What were you trying to do?" and "What confused you?"',
          'What they struggle with is not their fault — it\'s a design signal',
        ],
      },
      {
        type: 'project',
        label: '— Assignment',
        heading: 'Run a 5–10 Minute Playtest Session',
        body: 'Have someone play your game for 5–10 minutes. Watch them play without giving instructions. Take notes the whole time. You\'ll write up your findings and share them during the May 16 Saturday session.',
      },
      {
        type: 'concept',
        label: '— Your Log',
        heading: 'What to Write in Your Playtest Log',
        items: [
          'Who played your game and for how long?',
          'What did they struggle with or find confusing? List 3+ specific moments with detail',
          'What did they seem to enjoy? What made them smile, laugh, or try again?',
          'What did they ask you that you couldn\'t answer? These are design gaps.',
          'List 2–3 specific changes you want to make based on what you observed',
        ],
      },
      {
        type: 'challenge',
        challengeNum: 6,
        label: '— Submit',
        heading: 'Submit Before May 16',
        body: 'Bring your playtest log to the May 16 session. You\'ll share findings in a group discussion — we\'ll look for patterns across everyone\'s logs. The struggles that show up in every game are the most interesting ones.',
      },
    ] as Slide[],
  },

  // ══════════════════════════════════════════════════════════
  //  ASYNC 3 — Art & Assets
  // ══════════════════════════════════════════════════════════
  {
    id: 'async3',
    num: 6,
    title: 'Art & Assets',
    theme: 'Async · Optional · ~30 min',
    slides: [
      {
        type: 'title',
        heading: 'Art &\nAssets',
        label: 'Async 3 · Optional · No Submission Needed',
      },
      {
        type: 'visual',
        label: '— Free Tools',
        heading: 'Make Your Game Look Like Yours',
        body: 'You don\'t need to be an artist. You need to be consistent. These tools are used by real indie developers and require zero installation.',
        cards: [
          { icon: '🎨', title: 'Piskel', body: 'Free browser-based pixel art editor. Make characters, tiles, and sprite animations. Export as PNG spritesheet — import directly into Godot\'s AnimatedSprite2D. piskelapp.com' },
          { icon: '🎮', title: 'itch.io Assets', body: 'Massive library of free game asset packs — sprites, tilesets, fonts, UI. Search "free assets" and filter by license. Drop them straight into your Godot res:// folder.' },
          { icon: '🔊', title: 'freesound.org', body: 'Free sound effects library. Search for anything: footsteps, coins, explosions. Download as .wav or .ogg and load into AudioStreamPlayer in Godot.' },
          { icon: '📱', title: 'Voice Memo', body: 'Record your own SFX with your phone. Tap a table = footstep. Crinkle paper = fire. Blow into the mic = wind. Import the file into Godot as an AudioStream.' },
        ],
      },
      {
        type: 'concept',
        label: '— Importing into Godot',
        heading: 'Using Custom Art in Your Game',
        body: 'Drop any PNG into your project\'s res:// folder (via the FileSystem dock). Godot auto-imports it. Then:',
        items: [
          'Sprite: drag it directly onto a Sprite2D node\'s Texture property in the Inspector',
          'Animation frames: open AnimatedSprite2D → SpriteFrames → drag frames in one by one',
          'Spritesheet (e.g. from Piskel): use Sprite2D → Hframes and Vframes to slice it',
          'Sound: drag .wav or .ogg onto AudioStreamPlayer\'s Stream property in the Inspector',
          'Font: Theme Overrides → Fonts → Load → select your .ttf file',
          'Keep art consistent — same pixel size, same color palette across all sprites',
        ],
      },
      {
        type: 'challenge',
        challengeNum: 7,
        label: '— Challenge 07',
        heading: 'Create at Least One Asset',
        body: 'Make something for your game before the next Saturday session. A pixel art character in Piskel, a custom title screen sketch, or a sound effect recorded on your phone. No submission needed — just bring what you made and show it off.',
      },
    ] as Slide[],
  },

  // ══════════════════════════════════════════════════════════
  //  SATURDAY 1 — Core Loop
  // ══════════════════════════════════════════════════════════
  {
    id: 'sat1',
    num: 7,
    title: 'Core Loop',
    theme: 'May 2 · Virtual · Saturday',
    slides: [
      {
        type: 'title',
        heading: 'Core\nLoop',
        label: 'Saturday 1 · May 2 · Virtual · 10am–12pm',
      },
      {
        type: 'question',
        label: '— GDD Feedback',
        heading: 'What did instructors notice in your Game Design Docs?',
        body: 'Instructors reviewed every GDD and left written feedback. Before we build, let\'s talk about patterns.',
        items: [
          'Which part of your GDD changed the most after you started building in April?',
          'What\'s one mechanic in your GDD that you\'re not sure how to code yet?',
          'Did anything turn out harder or easier than you expected when you opened Godot?',
        ],
      },
      {
        type: 'concept',
        label: '— Design',
        heading: 'What Is a Core Loop?',
        body: 'A core loop is the action a player repeats over and over. Action → reward → repeat. In Dodge the Creeps: move → dodge mob → survive longer → score goes up → repeat. Every great game has one tight loop.',
        items: [
          'Platformer: jump → land on platform → collect coin → reach next platform → repeat',
          'Shooter: aim → shoot → enemy dies → new enemy spawns → repeat',
          'Puzzle: observe → move piece → check result → observe again → repeat',
          'A bad loop: action → nothing happens. Player stops.',
          'A good loop: action → immediate feedback → player wants to do it again',
          'Ask yourself right now: what is the ONE thing the player does most in my game?',
        ],
      },
      {
        type: 'concept',
        label: '— Build',
        heading: 'Win Screen, Lose Screen & UI',
        body: 'Today\'s goal: a stranger can pick up your game and know what to do, whether they won, and whether they lost. Here\'s how to wire it up in Godot:',
        items: [
          'Win condition: use an Area2D with body_entered signal — when player enters it, call game_won()',
          'Lose condition: same as Dodge the Creeps — player emits hit signal → game_over()',
          'Win screen: show a CanvasLayer with a Label ("You Win!") and a restart Button',
          'Lose screen: same structure with "Game Over" text',
          'Score counter: var score = 0 in Main → increment in a Timer timeout → display via Label.text = str(score)',
          'Health bar: use a ProgressBar node → set value = current_health, max_value = max_health',
          'Timer: Label.text = str(int(time_left)) updated each frame in _process()',
        ],
      },
      {
        type: 'challenge',
        challengeNum: 8,
        label: '— Challenge 08',
        heading: 'Make Something Reset',
        body: 'When the player loses or wins, the game must be able to restart cleanly. Use get_tree().reload_current_scene() for a full reset, or get_tree().change_scene_to_file("res://main.tscn"). Test it: lose the game, press restart, verify score resets to 0, player returns to start position, and all enemies are gone.',
      },
    ] as Slide[],
  },

  // ══════════════════════════════════════════════════════════
  //  SATURDAY 2 — Levels & Polish
  // ══════════════════════════════════════════════════════════
  {
    id: 'sat2',
    num: 8,
    title: 'Levels & Polish',
    theme: 'May 9 · Virtual · Saturday',
    slides: [
      {
        type: 'title',
        heading: 'Levels &\nPolish',
        label: 'Saturday 2 · May 9 · Virtual · 10am–12pm',
      },
      {
        type: 'concept',
        label: '— Design',
        heading: 'Difficulty Scaling',
        body: 'Level 1 teaches. Level 2 tests. If both levels feel identical your game has no arc. Good scaling respects the player — harder without feeling cheap.',
        items: [
          'Introduce one new mechanic per level — don\'t throw everything at once',
          'Increase enemy speed: instead of randf_range(150, 250), use randf_range(200, 320) in Level 2',
          'In platformers: shorter platforms, longer gaps, faster moving obstacles',
          'Use safe spaces in Level 1 to let the player practice — remove them in Level 2',
          'Never punish the player for something the game didn\'t teach them first',
          'Playtest your second level with fresh eyes — 5 deaths in a row = too hard',
        ],
      },
      {
        type: 'concept',
        label: '— Scenes',
        heading: 'Building a Second Level in Godot',
        body: 'Each level is its own scene in Godot. Here\'s the pattern for loading Level 2 after Level 1 is completed:',
        items: [
          'Duplicate level1.tscn in the FileSystem → rename to level2.tscn',
          'Open level2.tscn and modify the layout — different platforms, harder enemy paths',
          'In level1.tscn: create an Area2D "FinishLine" at the end of the level',
          'Connect body_entered signal to a function:',
          'func _on_finish_line_body_entered(body):',
          '    if body.name == "Player":',
          '        get_tree().change_scene_to_file("res://level2.tscn")',
          'The player carries over automatically — their scene is instanced fresh in level2.tscn',
          'You can pass data between scenes using a Global autoload script (Project → Project Settings → Autoload)',
        ],
      },
      {
        type: 'video',
        label: '— Audio',
        heading: 'Adding Sound Effects in Godot',
        body: 'Audio transforms a game. Godot\'s AudioStreamPlayer makes it easy. Add one node, load a file, call .play().',
        videos: [
          { label: 'Godot Audio Docs — AudioStreamPlayer', url: 'https://docs.godotengine.org/en/stable/tutorials/audio/audio_streams.html' },
          { label: 'freesound.org — Free SFX Library (CC licensed)', url: 'https://freesound.org' },
          { label: 'itch.io — Free Audio Asset Packs', url: 'https://itch.io/game-assets/free/tag-audio' },
        ],
      },
      {
        type: 'challenge',
        challengeNum: 9,
        label: '— Challenge 09',
        heading: 'Fix Your Top Bug with a Partner',
        body: 'Pair up. Spend 10 minutes playing each other\'s games and identifying the single most annoying bug. Then switch back and fix yours — with your partner watching. Two sets of eyes find issues one never would. When you fix it, share what the bug was and what caused it in the group chat.',
      },
    ] as Slide[],
  },

  // ══════════════════════════════════════════════════════════
  //  SATURDAY 3 — Art & Story
  // ══════════════════════════════════════════════════════════
  {
    id: 'sat3',
    num: 9,
    title: 'Art & Story',
    theme: 'May 16 · Virtual · Saturday',
    slides: [
      {
        type: 'title',
        heading: 'Art &\nStory',
        label: 'Saturday 3 · May 16 · Virtual · 10am–12pm',
      },
      {
        type: 'question',
        label: '— Playtest Share-Out',
        heading: 'What did people struggle with in your game?',
        body: 'Share your playtest logs. We\'re looking for patterns across everyone\'s findings.',
        items: [
          'What was the most common thing your playtester did that you didn\'t expect?',
          'What part of your game did they understand immediately — without being told?',
          'What\'s the one change you made, or want to make, based on what you saw?',
        ],
      },
      {
        type: 'concept',
        label: '— Pixel Art',
        heading: 'Pixel Art Basics with Piskel',
        body: 'Pixel art is the native art style of 2D indie games. Low resolution forces intentional choices — every pixel matters. Work small, stay consistent.',
        items: [
          'Character size: 16×16 or 32×32 pixels. Tile size: 16×16.',
          'Limit palette: 4–8 colors per character. More = noise, not detail.',
          'Add a 1px dark outline around your character — it reads on any background',
          'In Piskel: create 2–4 frames for a walk cycle. Export as PNG spritesheet.',
          'In Godot: AnimatedSprite2D → SpriteFrames → Add Frames from Spritesheet → set Hframes/Vframes to slice it',
          'For tiles: use a TileMap node — add your tileset, paint the level, done',
          'Consistency matters more than quality. 8-color palette used perfectly beats 64-color palette used randomly.',
        ],
      },
      {
        type: 'concept',
        label: '— UI',
        heading: 'Title Screen + Narrative in Godot',
        body: 'Your game needs a title screen scene and at least one narrative moment. Here\'s the minimal setup:',
        items: [
          'Create title_screen.tscn → CanvasLayer → Label (game name) + Button ("Start Game")',
          'Button pressed signal: get_tree().change_scene_to_file("res://level1.tscn")',
          'Set title_screen.tscn as Main Scene in Project Settings',
          'Dialogue: add a Label node above an NPC or at level start',
          'Show/hide on trigger: $DialogueLabel.show() in an Area2D body_entered signal',
          'Cutscene: use a Tween node to animate a Label or ColorRect in sequence',
          'Ending: create an end_screen.tscn scene — same pattern as the title screen',
        ],
      },
      {
        type: 'challenge',
        challengeNum: 10,
        label: '— Challenge 10',
        heading: 'Breakout Room Playtest',
        body: 'Split into groups of 2–3. Each person has 10 minutes to play a partner\'s game while the developer watches silently and takes notes. Then 3 minutes of feedback: one thing that worked, one question you had, one suggestion. Rotate until everyone has played at least one other game.',
      },
      {
        type: 'visual',
        label: '— Identity',
        heading: 'What Makes a Game Feel Like Yours',
        body: 'The best indie games have a clear identity. You feel the developer in the choices they made.',
        cards: [
          { icon: '🎨', title: 'Visual Consistency', body: 'All art uses the same palette and scale. One mismatched asset (even a placeholder) breaks immersion instantly.' },
          { icon: '✍️', title: 'Voice', body: 'Your error messages, dialogue, and UI text sound like a person — ideally, like you. Personality in copy is free.' },
          { icon: '🎵', title: 'Audio Mood', body: 'Music and SFX that match the feeling of the game. Upbeat music in a horror game is a design mistake, not a quirk.' },
          { icon: '💡', title: 'One Weird Thing', body: 'The mechanic, visual, or story beat that only your game has. This is the thing people describe when they tell others about it.' },
        ],
      },
    ] as Slide[],
  },

  // ══════════════════════════════════════════════════════════
  //  SATURDAY 4 — Final Showcase
  // ══════════════════════════════════════════════════════════
  {
    id: 'sat4',
    num: 10,
    title: 'Final Showcase',
    theme: 'May 23 · Virtual · Saturday',
    slides: [
      {
        type: 'title',
        heading: 'Final\nShowcase',
        label: 'Saturday 4 · May 23 · Virtual · 10am–12pm',
      },
      {
        type: 'concept',
        label: '— Final Sprint',
        heading: '30-Minute Polish Sprint',
        body: 'Last build time before the showcase. Instructors are circulating to help you prioritize. Rule: do not add new features. Fix what\'s there.',
        items: [
          'Does the game start cleanly from the title screen? Fix if not — this is the first impression.',
          'Does the game end clearly — win or lose — without crashing? Fix if not.',
          'Is there at least one sound effect? If not, add one AudioStreamPlayer now — 5 minutes.',
          'Does the game reset properly when you restart? Test it twice.',
          'Export to HTML5 right now if you haven\'t — you want the export working before you present.',
          'Small, complete, and polished > large, broken, and ambitious.',
        ],
      },
      {
        type: 'concept',
        label: '— Presentation',
        heading: 'How to Present Your Game',
        body: 'You have 3 minutes. A volunteer plays your game live while you narrate. Here is the exact structure that works:',
        items: [
          'Open with one sentence: "My game is [name], a [genre] where you [goal]"',
          'Let the gameplay run — narrate what\'s happening, don\'t apologize for bugs',
          '"Right now [volunteer] is trying to [thing] — watch what happens when..."',
          'Share one thing you\'re proud of: a mechanic, a visual, a moment that works',
          'Share one v2 idea: shows you\'re thinking like a designer, not just a coder',
          'Close: "That\'s [game name]. Thanks for playing."',
          'Three minutes is more than enough if you follow this structure.',
        ],
      },
      {
        type: 'challenge',
        challengeNum: 11,
        label: '— Showcase',
        heading: 'Present What You Built',
        body: 'Share your screen. Open your game. Hand it to a volunteer and narrate. Be proud — you built a game from scratch in 20 hours across 6 weeks. That\'s real. Whatever state it\'s in, it exists because you made decisions and followed through on them. That\'s what game developers do.',
      },
      {
        type: 'visual',
        label: '— What\'s Next',
        heading: 'Keep Building After This',
        body: 'The bootcamp ends today. The tools don\'t.',
        cards: [
          { icon: '🌐', title: 'Godot Community', body: 'forum.godotengine.org and the official Discord. Thousands of developers sharing code, tutorials, and project feedback.' },
          { icon: '🎮', title: 'Publish on itch.io', body: 'Export your game as HTML5 and upload for free. Share the link with anyone — no install required. Your game is already live.' },
          { icon: '🏁', title: 'Game Jams', body: 'Ludum Dare, GMTK Game Jam, itch.io jams. Build a game in 48–72 hours with a theme. The single fastest way to improve.' },
          { icon: '📚', title: 'GDQuest', body: 'gdquest.com — the best structured Godot tutorials on the internet. Free courses from absolute beginner to advanced systems.' },
        ],
      },
    ] as Slide[],
  },

];

export const GAMING_SESSION_MAP: Record<string, Lecture> = Object.fromEntries(
  GAMING_SESSIONS.map(s => [s.id, s])
);
